### ISSUE TITLE
Not sure how to build

### ISSUE THREAD

**Issue by ghost** [gdbinit/rootfool#1]
Hi,

This looks like a great tool, but I'm not sure how to build it. I've never worked with XCode before. Do I need the XCode full GUI version, or does just `xcodebuild` do the trick?

Thank you,
Teran

**Comment by gdbinit** [comment]
Sure, xcodebuild is able to build it without problems.
The kernel extension then needs to be manually code signed with a proper certificate.

**Comment by liuboflyon145** [comment]
hi,
I build the project with XCode ,but it is errors . this is error message "Failed to retrieve bundle information! Error 2 (No such file or directory)." . How to deal with this, give me help.

**Comment by gdbinit** [comment]
Hi,

You need to be more specific with the error message. I have no idea what is it related to.

**Comment by RaDeleon** [comment]
Pretty much you need a Mac developer account and $99 to built this

**Comment by gdbinit** [comment]
That is pretty much made clear in the README.
