### ISSUE TITLE
Appears broken on 10.11.2

### ISSUE THREAD

**Issue by JFKingsley** [gdbinit/rootfool#2]
Hey,

I recently installed this tool on my machine in order to test a piece of software that required SIP to be disabled. However, after installing the Kernel extension and rebooting, it appears that the app is not toggling SIP at all, with both checked and unchecked GUI allowing me to touch /System.

Is there some step i'm missing, or did a patch in .2 break compatibility?

Thank you for the great tool!

Jon

**Comment by gdbinit** [comment]
Hi,

No idea about what you are doing. There's no problem with up to .3.
You don't need to reboot, the kernel extension doesn't install and doesn't automatically load. It needs to be manually loaded each time.

fG!

**Comment by JFKingsley** [comment]
Ahh, that makes more sense then. Looks like all's working now!
