### ISSUE TITLE
Can someone just build binary for donwload?

### ISSUE THREAD

**Issue by ruthan** [gdbinit/rootfool#4]
If im understand it right, building such Utility or distributing kext is not ilegal, you need to have Apple developers certificate, so i hope that some have it and could share the result..

**Comment by gdbinit** [comment]
It's not clear that this utility would breach or not Apple's terms for the kernel extension code signing certificate so a signed binary will probably never be public unless someone wants to risk his certificate.

**Comment by realdannys** [comment]
@gdbinit exactly, which I'm not going to do, nor anyone else who's managed to get kext signing permission for their dev account. Which is why id really really love you to e-mail me the complied kext update :+1: :smile: Please!
